# Generated by Django 4.0.3 on 2022-05-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=124)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('GPA', models.FloatField()),
                ('dob', models.DateField()),
                ('level', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=240)),
                ('status', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('phone_Num', models.CharField(max_length=124)),
            ],
        ),
    ]
