# Generated by Django 4.0.4 on 2022-05-21 00:58

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_gpa_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('computer science', 'COMPUTER SCIENCE'), ('information system', 'INFORMATION SYSTEM'), ('information technology', 'INFORMATION TECHNOLOGY'), ('artificial intelligence', 'ARTIFICIAL INTELLIGENCE'), ('decision support system', 'DECISION SUPPORT SYSTEM')], default=contextlib.nullcontext, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=32),
        ),
    ]
